name: sert_update
on:
  schedule:
    - cron: '12 10 15 3-12/3 *'

jobs:
  run_crawler:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /app/newsmakers/
          docker compose run certbot renew
